version: "2"

run:
  timeout: 5m
  modules-download-mode: vendor

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - revive
    - gosec
    - nilerr

  settings:
    errcheck:
      check-type-assertions: true
    govet:
      enable-all: true
      disable:
        - fieldalignment
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: error-return
        - name: error-naming
        - name: exported
          disabled: true
        - name: increment-decrement
        - name: var-naming
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
    gosec:
      excludes:
        - G104
        - G304

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
  max-issues-per-linter: 50
  max-same-issues: 10
  exclude-dirs:
    - vendor
