name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Go service environment
        uses: ./.github/actions/setup-go-service
        with:
          download: false

      - name: Test
        env:
          GOFLAGS: -mod=vendor
        run: go test ./... -count=1

      - name: Build
        env:
          GOFLAGS: -mod=vendor
        run: go build ./...

  builder-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Verify builder image
        uses: ./.github/actions/build-docker-image
        with:
          dockerfile: images/go-service-builder/Dockerfile
          tags: service-runtime-go-builder:test
